import type { SwipeOrder, ActiveOrder, ManufacturerStats } from '@/types/orders'

export const mockSwipeOrders: SwipeOrder[] = [
  {
    id: 'sw-1',
    orderNumber: 'ORD-2024-041',
    title: 'Premium Cotton T-Shirts',
    category: 'Textiles & Garments',
    clientName: 'Rahul Sharma',
    clientCompany: 'FashionHub Pvt Ltd',
    clientRating: 4.7,
    clientVerified: true,
    quantity: 500,
    unit: 'Pieces',
    isFixedPrice: false,
    budgetMin: 45000,
    budgetMax: 60000,
    deliveryDate: '2024-03-15',
    deliveryDays: 18,
    deliveryLocation: 'Mumbai, Maharashtra',
    specialNotes: 'Need samples before bulk. Premium quality only.',
    isUrgent: false,
    isBulk: true,
    isNew: true,
    postedAt: '2024-01-20T10:00:00Z',
  },
  {
    id: 'sw-2',
    orderNumber: 'ORD-2024-042',
    title: 'PCB Assembly — IoT Sensors',
    category: 'Electronics & Components',
    clientName: 'Priya Mehta',
    clientCompany: 'TechVision Industries',
    clientRating: 4.9,
    clientVerified: true,
    quantity: 200,
    unit: 'Units',
    isFixedPrice: true,
    fixedPrice: 95000,
    deliveryDate: '2024-04-01',
    deliveryDays: 25,
    deliveryLocation: 'Bengaluru, Karnataka',
    specialNotes: 'All components to be sourced by manufacturer. ISO certified factory required.',
    isUrgent: true,
    isBulk: false,
    isNew: true,
    postedAt: '2024-01-20T08:30:00Z',
  },
  {
    id: 'sw-3',
    orderNumber: 'ORD-2024-043',
    title: 'MS Steel Brackets — Galvanized',
    category: 'Hardware & Metals',
    clientName: 'Amit Patel',
    clientCompany: 'BuildRight Corp',
    clientRating: 4.3,
    clientVerified: false,
    quantity: 1000,
    unit: 'Pieces',
    isFixedPrice: false,
    budgetMin: 30000,
    budgetMax: 40000,
    deliveryDate: '2024-02-28',
    deliveryDays: 12,
    deliveryLocation: 'Pune, Maharashtra',
    specialNotes: '5mm thickness. Hot dip galvanized. BIS marked preferred.',
    isUrgent: true,
    isBulk: true,
    isNew: false,
    postedAt: '2024-01-19T15:00:00Z',
  },
  {
    id: 'sw-4',
    orderNumber: 'ORD-2024-044',
    title: 'Wooden Packaging Boxes',
    category: 'Furniture & Wood',
    clientName: 'Sneha Kapoor',
    clientCompany: 'EcoPackage Ltd',
    clientRating: 4.6,
    clientVerified: true,
    quantity: 300,
    unit: 'Pieces',
    isFixedPrice: false,
    budgetMin: 18000,
    budgetMax: 25000,
    deliveryDate: '2024-03-30',
    deliveryDays: 20,
    deliveryLocation: 'Delhi, NCR',
    specialNotes: '30x20x15 cm. Pine wood, varnished finish.',
    isUrgent: false,
    isBulk: false,
    isNew: true,
    postedAt: '2024-01-20T11:00:00Z',
  },
  {
    id: 'sw-5',
    orderNumber: 'ORD-2024-045',
    title: 'Automotive Brake Pads',
    category: 'Automotive Parts',
    clientName: 'Vikram Singh',
    clientCompany: 'AutoZone India',
    clientRating: 4.8,
    clientVerified: true,
    quantity: 2000,
    unit: 'Sets',
    isFixedPrice: true,
    fixedPrice: 180000,
    deliveryDate: '2024-03-10',
    deliveryDays: 15,
    deliveryLocation: 'Chennai, Tamil Nadu',
    specialNotes: 'Must meet AIS-141 standards. OEM quality required.',
    isUrgent: true,
    isBulk: true,
    isNew: false,
    postedAt: '2024-01-18T09:00:00Z',
  },
]

export const mockActiveOrders: ActiveOrder[] = [
  {
    id: 'act-1',
    orderNumber: 'ORD-2024-031',
    title: 'Denim Jeans — 300 Units',
    category: 'Textiles & Garments',
    clientName: 'Rohan Gupta',
    clientCompany: 'StyleWear India',
    clientRating: 4.5,
    clientVerified: true,
    quantity: 300,
    unit: 'Pieces',
    isFixedPrice: false,
    budgetMin: 60000,
    budgetMax: 80000,
    deliveryDate: '2024-02-20',
    deliveryDays: 12,
    deliveryLocation: 'Mumbai, Maharashtra',
    isUrgent: false,
    isBulk: false,
    isNew: false,
    postedAt: '2024-01-05T10:00:00Z',
    status: 'manufacturing',
    acceptedAt: '2024-01-10T12:00:00Z',
    agreedPrice: 72000,
    manufacturingStarted: true,
    escrowAmount: 72000,
    bidId: 'bid-act-1',
  },
  {
    id: 'act-2',
    orderNumber: 'ORD-2024-028',
    title: 'HDPE Plastic Containers',
    category: 'Plastics & Polymers',
    clientName: 'Meena Agarwal',
    clientCompany: 'Packrite Solutions',
    clientRating: 4.2,
    clientVerified: false,
    quantity: 500,
    unit: 'Pieces',
    isFixedPrice: true,
    fixedPrice: 42000,
    deliveryDate: '2024-02-10',
    deliveryDays: 5,
    deliveryLocation: 'Ahmedabad, Gujarat',
    isUrgent: true,
    isBulk: true,
    isNew: false,
    postedAt: '2023-12-28T08:00:00Z',
    status: 'shipped',
    acceptedAt: '2024-01-02T10:00:00Z',
    agreedPrice: 42000,
    manufacturingStarted: true,
    manufacturingCompletedAt: '2024-01-18T16:00:00Z',
    escrowAmount: 42000,
    bidId: 'bid-act-2',
  },
]

export const mockStats: ManufacturerStats = {
  totalEarnings: 285000,
  inEscrow: 114000,
  activeOrders: 2,
  completedOrders: 14,
  acceptanceRate: 68,
  avgResponseTime: '2.4 hrs',
  rating: 4.7,
  totalReviews: 31,
}
